version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get -y -qq install python python-pip
            sudo pip install -qq awscli
      - run:
          name: Install Serverless framework
          command: sudo npm install -g serverless
      - run:
          name: Deploy website
          command: |
            OUTPUT="$(serverless deploy --verbose --stage=master)"
            aws s3 sync ./public s3://$(echo $OUTPUT | node ./.circleci/regex.js WebsiteS3BucketName) --delete
            aws cloudfront create-invalidation --distribution-id $(echo $OUTPUT | node ./.circleci/regex.js CloudfrontDistributionId) --paths=/*
            echo "$OUTPUT"

workflows:
  version: 2
  continuous-integration:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
